#!/bin/bash
# VIDEO COMPRESSION GUIDE FOR PORTFOLIO
# This script provides optimal settings for compressing portfolio videos

echo "==================================="
echo "VIDEO COMPRESSION GUIDE"
echo "==================================="
echo ""
echo "GOAL: Reduce each video to 1-2 MB for fast loading"
echo ""

echo "=== OPTION 1: Using FFmpeg (Recommended) ==="
echo ""
echo "For 480p (Faster compression, good quality):"
echo "ffmpeg -i input.mp4 -vf scale=854:480 -c:v libx264 -crf 28 -preset fast -c:a aac -b:a 96k output_480p.mp4"
echo ""
echo "For 720p (Slightly larger, better quality):"
echo "ffmpeg -i input.mp4 -vf scale=1280:720 -c:v libx264 -crf 26 -preset fast -c:a aac -b:a 128k output_720p.mp4"
echo ""
echo "For 30 FPS (Reduce frame rate for smaller size):"
echo "ffmpeg -i input.mp4 -vf scale=854:480,fps=30 -c:v libx264 -crf 28 -preset fast -c:a aac -b:a 96k output_30fps.mp4"
echo ""

echo "=== OPTION 2: Using HandBrake (GUI Tool) ==="
echo ""
echo "1. Open HandBrake"
echo "2. Load your video"
echo "3. Select 'Fast 720p30' preset (or create custom)"
echo "4. Set Video Codec: H.264"
echo "5. Set RF: 26-28 (higher = smaller file, lower quality)"
echo "6. Set Audio bitrate: 96-128 kbps"
echo "7. Start encode"
echo ""

echo "=== TARGET SPECIFICATIONS ==="
echo ""
echo "Resolution:     480p (854x480) or 720p (1280x720)"
echo "Frame Rate:     24 or 30 fps (NOT 60)"
echo "Codec:          H.264 (MP4) or VP9 (WebM)"
echo "RF/Quality:     26-28 (high compression)"
echo "Audio Bitrate:  96-128 kbps"
echo "Target Size:    1-2 MB per video"
echo ""

echo "=== VERIFICATION ==="
echo ""
echo "Check file size and properties:"
echo "ffprobe -v quiet -print_format json -show_format -show_streams input.mp4"
echo ""

echo "=== EXPECTED RESULTS ==="
echo ""
echo "Original 60fps 4K:  ~100-200 MB"
echo "Optimized 480p 30fps: ~1-2 MB"
echo "Compression Ratio: 98-99%"
echo "Quality: Still Very Good for portfolio"
echo ""
